name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy code to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@13.60.87.195 << 'EOF'
          cd /home/ubuntu/fastapi-book-project
          git pull origin main
          source /home/ubuntu/fastapi-book-project/venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart fastapi
        EOF
